### ISSUE TITLE
Code Execution Time

### ISSUE THREAD

**Issue by LyndonCrouch** [sxn5959/Data-Science-Project#2]
After fixing error and expanding mapping, adding factorize; running models takes ~600MB ram and takes very long to run

**Comment by sxn5959** [comment]
I think we should try to split the the cleaned data set in small batches sequentially if possible instead of training the entire cleaned dataset at once.

**Comment by LyndonCrouch** [comment]
SVC still takes ~six and half minutes on my desktop to execute, but it seems much better. Since SVC doesn't seem to be the best model, I commented out the PlotSVC. That cuts the execute time down from like 2 hours to 7 minutes
